# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a8437930d37b4b24d068a91d2491f4664f57b6cffc6ac9445d543bea4627fea1ce0be2879c4bb7eba832071d03eb368c36151948f957014cad2ba4149e5d588

test:
  secret_key_base: 931debb30b7d694e1749968b95792c1d8fe70586e73247c645ec3b63552f942dcd387518178bef7b6cbdcf866f16a90c7cad6bffa114b30ba88b1047a729026a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
